### ISSUE TITLE
how to view text Justified (build for android)?

### ISSUE THREAD

**Issue by hoangphuongcs** [fram-x/react-native-styled-text#20]

**Comment by bjornegil** [comment]
Do you mean like left or right aligned?

**Comment by hoangphuongcs** [comment]
> Do you mean like left or right aligned?

y, here  for a sample

![image](https://user-images.githubusercontent.com/4811620/57501143-8d5f1300-7310-11e9-869b-e50f0bc0ae2a.png)

**Comment by bjornegil** [comment]
StyledText just transforms to nested RN Text components, so you can apply the same formatting as you can do for RN Text
